"""Self Improvement Agent component."""

from __future__ import annotations

import logging
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from src.config.settings import get_settings
from src.db.repositories.learning_repo import LearningRepository
from src.meta.performance_monitor import PerformanceMonitor

logger = logging.getLogger(__name__)


class OptimizationProposal(BaseModel):
    """A proposal for system optimization generated by the Self Improvement Agent."""
    
    title: str = Field(description="Title of the optimization.")
    description: str = Field(description="Detailed explanation of what should be optimized and why.")
    target_component: str = Field(description="The system component to be optimized.")
    expected_impact: str = Field(description="Expected benefit of the optimization.")
    confidence: float = Field(description="Confidence that this optimization will succeed (0.0 to 1.0).")


class SelfImprovementAgent:
    """Background agent that reviews performance data and policies to propose system optimizations."""

    def __init__(
        self,
        learning_repo: LearningRepository,
        performance_monitor: PerformanceMonitor,
        llm: Any = None,
    ) -> None:
        self.learning_repo = learning_repo
        self.performance_monitor = performance_monitor
        self.settings = get_settings()

        if llm is None:
            from langchain_anthropic import ChatAnthropic
            self.llm = ChatAnthropic(
                model=self.settings.anthropic_model,
                api_key=self.settings.anthropic_api_key.get_secret_value(),
                temperature=0.2,
            )
        else:
            self.llm = llm

        self.structured_llm = self.llm.with_structured_output(OptimizationProposal)

    async def analyze_and_propose(self) -> OptimizationProposal | None:
        """Analyze recent policies and metrics, and propose an optimization."""
        logger.info("Starting self-improvement analysis")
        
        # Fetch active policies
        policies = await self.learning_repo.get_active_policies()
        policies_summary = "\n".join([f"- {p.name}: {p.condition} -> {p.action}" for p in policies[:5]])
        
        system_prompt = (
            "You are the Self-Improvement Agent for an autonomous AGI-inspired platform. "
            "Your goal is to review the current active policies and system performance data "
            "to propose a concrete, actionable optimization to the system's architecture, "
            "prompts, or hyperparameters."
        )

        user_content = (
            f"Active Policies:\n{policies_summary}\n\n"
            "Based on these learned policies, what structural or systemic optimization would you propose?"
        )

        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_content),
        ]

        try:
            result: OptimizationProposal = await self.structured_llm.ainvoke(messages)
            logger.info(f"Generated optimization proposal: {result.title}")
            return result
        except Exception as e:
            logger.error(f"Self-improvement analysis failed: {e}")
            return None
